<?php

namespace AppBundle\Repository;

/**
 * CandidatoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CandidatoRepository extends \Doctrine\ORM\EntityRepository
{
}
