<?php

namespace AppBundle\Repository;

/**
 * CondicaoCotistaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CondicaoCotistaRepository extends \Doctrine\ORM\EntityRepository
{
}
