<?php

namespace AppBundle\Repository;

/**
 * GrupoDeUsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrupoDeUsuarioRepository extends \Doctrine\ORM\EntityRepository
{
}
